# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fBMIKPloLbt7aSNwB9vnNjgvGIyTA2MYRrdMMMK1TZlRevyPIILA6PA7kqlXnKmAV/5/GwrWEO7FplW1Llr2/cWX1ORRCA6ET0UtAkY/0oso5g4ycrhY26p61NEx/7ApDf9YCiCWGar7pkPqGnbhRJaledstHOYZrk3uiBgK9plnyrdaWuQN5fZ1Nu/dWnvF+jnQSFk5/0dVf7M6fsCSb9jh+c5iPOlR1c9vb9Nmx6NUc5ih5uYd+w3/7te+KyQrfJnPbRb+pilL79d1Tqa9EEviB6jrp2EG7lxdrgxyasPRmCgNcStyEsE2IkrkfR3P6E8E2ybjWmOFWstYtQKCAd2xD3d+FxEB6+Hfo3vNf3NRLwxETP+UYzoqYbyJXgbWjw6leQE82zJYIffpFp/GWpDIIyMZimOs8BoCUOyNsFHRa4Pf5/HRUxKx7A/2bT2uf+7ttFaYneB2of3ceNMTXrHTLw4sFnlZNIAeej9KyLITf45uaI5Wak9ZkSC8YneVi5LE65b0GcHhEl3+IvBIJecY1j3qUryTL/88SkKdYpEWl5esT8s+9hEjGyB0Hm6QKeT4zGkDZWTR8eYHYA3hSlF7uY6r05Yo7hsfZobL/AgzYhIT/v5eL0nq2Sjxa/8u5LgiZIDypBuKAPB3JWQzVAV1gu0Y2VupTBuLbWeY8iw="


before_install:
    # Remove homebrew.
    - brew remove --force --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
