# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fBMIKPloLbt7aSNwB9vnNjgvGIyTA2MYRrdMMMK1TZlRevyPIILA6PA7kqlXnKmAV/5/GwrWEO7FplW1Llr2/cWX1ORRCA6ET0UtAkY/0oso5g4ycrhY26p61NEx/7ApDf9YCiCWGar7pkPqGnbhRJaledstHOYZrk3uiBgK9plnyrdaWuQN5fZ1Nu/dWnvF+jnQSFk5/0dVf7M6fsCSb9jh+c5iPOlR1c9vb9Nmx6NUc5ih5uYd+w3/7te+KyQrfJnPbRb+pilL79d1Tqa9EEviB6jrp2EG7lxdrgxyasPRmCgNcStyEsE2IkrkfR3P6E8E2ybjWmOFWstYtQKCAd2xD3d+FxEB6+Hfo3vNf3NRLwxETP+UYzoqYbyJXgbWjw6leQE82zJYIffpFp/GWpDIIyMZimOs8BoCUOyNsFHRa4Pf5/HRUxKx7A/2bT2uf+7ttFaYneB2of3ceNMTXrHTLw4sFnlZNIAeej9KyLITf45uaI5Wak9ZkSC8YneVi5LE65b0GcHhEl3+IvBIJecY1j3qUryTL/88SkKdYpEWl5esT8s+9hEjGyB0Hm6QKeT4zGkDZWTR8eYHYA3hSlF7uY6r05Yo7hsfZobL/AgzYhIT/v5eL0nq2Sjxa/8u5LgiZIDypBuKAPB3JWQzVAV1gu0Y2VupTBuLbWeY8iw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
