travis:
  secure:
    BINSTAR_TOKEN: a+M4n0aBoHwVE1nDr9TfOeC+68krFHfTzrfrMs5bqOhzvhNWR+MAq+2/Ar/ZHs6Zmi/ij8MUQUvOaUQNC9UYjR/QlM3kMqvJJ7MzkHb/Lecni4fKZazrkOUebfS9H1gXaJhAPJO1+uwDxtBDe11+5r3XD1nmbm0JQTnuDuSr9HFLGWnaWRG5dn4ndapSejCL/jfF8+pQqCsjIBQ/4HB9SDqK41XJoIYfMuF5a5qi+FB1jdRNZxuaEbWgE3SQwfDfDFZLhZqVG0E+aHwYMybnboTZn+Y2f0x1ZrpB1WwxXi2B84WolA/sWfH6hal8cG/Q+2uumVHXx3vVKtGxGpDtKQspY5xB7ZKq2UCBW7gvMICHHsgj96lqlI8XiZareCvhu6wkcFqNsXIn5gaEsKA+e6HLrgrlWsXCaeIxDXMHVYH4c0RxMelVBNSx+cranBMWN5NjRLR6MsNufxuH+yONm66yK057SK49CcAhwnOQFX7jI5agH5fdLqlUnXFe919mh+9mVVzXKGO4LUc55uaQlHH9pdWhhnns6hSxSvfF5SySDhxRp+qM1D7M57UpWcqSFYK8v7bj0MS8vNedn8tqkrNl/CUv3rXVGIFDD/F/OODO3CXPpgGMOB/q08SVcHzAMS2kn6A898r0Jdb9up+begm61S9PEyQxyi7q1c+6kMo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
